name: latest-builds

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Install zip
        run: sudo apt-get install zip
      - name: Pack the artifacts
        run: zip target/debug/tsls-linux-x86_64.zip target/debug/tsls
      - uses: actions/upload-artifact@v2
        with:
          name: tsls-linux-x86_64
          path: target/debug/tsls-linux-x86_64.zip
          retention-days: 1
  macos:
    # if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Pack the artifacts
        run: zip target/debug/tsls-macos-x86_64.zip target/debug/tsls
      - uses: actions/upload-artifact@v2
        with:
          name: tsls-macos-x86_64
          path: target/debug/tsls-macos-x86_64.zip
          retention-days: 1

  publish:
    needs: [linux, macos]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/download-artifact@v2
      - name: Pack the artifacts
        run: zip tsls-macos-x86_64.zip tsls-macos-x86_64
      - name: Pack the artifacts
        run: zip tsls-linux-x86_64.zip tsls-linux-x86_64
      - name: Show all files
        run: ls -l
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Develpment build"
          files: |
            *.zip"
            tsls-linux-x86_64
            tsls-macos-x86_64
            tsls-macos-x86_64.zip
            tsls-linux-x86_64.zip
